# Generated by Django 4.0 on 2021-12-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventories',
            new_name='inventory',
        ),
    ]
