# Generated by Django 4.0 on 2021-12-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_inventories_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
